### ISSUE TITLE
Information in Cloudflare

### ISSUE THREAD

**Issue by aguerrave** [hbwheat/Raspberry-Pi-Setup#4]
Can you explain what information I should put in:
URL0_SAN= ??
URL_IP= ??

**Comment by hbwheat** [comment]
@aguerrave, yes, let me edit the readme for that as others may have the same question. Sorry for not doing that sooner. I'll provide a sample of my .env file.

**Comment by hbwheat** [comment]
@aguerrave  I updated the readme for Traefik: 

`URL0_SAN defines a designation for Traefik to route based on a http request for an address. URL0 is simply the first URL to route ie traefik.site.local , and URL_IP is the IP address for routing as well ie 192.168.1.12.

When a request hits traefik at traefik.site.local traefik will route to the service identified in the docker-compose file label.

Refer to the docker-compose.yaml file labels section: - "traefik.http.routers.api.rule=Host(`${URL0_SAN}`)"

Remember .env files use a simple key-value pair and docker-compose will pull the value from the key associated with $ or ${key}.`

**Comment by aguerrave** [comment]
Thank for the answer, but i still get error, now the errors are the
cf api_key,
cd_dns_api
cf_zone_api
where do you get thats key?

Regards.
thk

PD: i use this link 
https://aws1.discourse-cdn.com/cloudflare/original/3X/4/a/4ab81fec390bdbf70a175dc327a477a2e080c505.png

> {"level":"error","msg":"Unable to obtain ACME certificate for domains \"monitor.mydomain.com.ve\": unable to generate a certificate for the domains [monitor.mydomain.com.ve]: acme: Error -\u003e One or more domains had a problem:\n[monitor.mydomain.com.ve] [monitor.mydomain.com.ve] acme: error presenting token: cloudflare: failed to find zone mydomain.com.ve.: ListZonesContext command failed: error from makeRequest: HTTP status 403: insufficient permissions\n","providerName":"mydnschallenge.acme","routerName":"api","rule":"Host(`monitor.mydomain.com.ve`)","time":"2020-02-26T19:35:42Z"}
